# Generated by Django 3.0.6 on 2020-05-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='level',
        ),
    ]
