# Generated by Django 3.0.6 on 2020-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior deweloper'), ('M', 'Middle deweloper'), ('S', 'Senior deweloper')], default='J', max_length=1),
        ),
    ]
